# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import car_predictor_pb2 as car__predictor__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in car_predictor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CarPriceServiceStub(object):
    """service that i buid this app for
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictPrice = channel.unary_unary(
                '/car_prediction.CarPriceService/PredictPrice',
                request_serializer=car__predictor__pb2.CarFeaturesRequest.SerializeToString,
                response_deserializer=car__predictor__pb2.PriceResponse.FromString,
                _registered_method=True)


class CarPriceServiceServicer(object):
    """service that i buid this app for
    """

    def PredictPrice(self, request, context):
        """the method used to predict the price of the car 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarPriceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictPrice,
                    request_deserializer=car__predictor__pb2.CarFeaturesRequest.FromString,
                    response_serializer=car__predictor__pb2.PriceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'car_prediction.CarPriceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('car_prediction.CarPriceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CarPriceService(object):
    """service that i buid this app for
    """

    @staticmethod
    def PredictPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/car_prediction.CarPriceService/PredictPrice',
            car__predictor__pb2.CarFeaturesRequest.SerializeToString,
            car__predictor__pb2.PriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
