FROM python:3.9-slim

WORKDIR /app

# تثبيت المكتبات الأساسية
RUN pip install --no-cache-dir \
    pandas \
    scikit-learn \
    joblib \
    grpcio \
    grpcio-tools

# نسخ ملفات الموديل والسكربتات
# تأكد إن أسماء الملفات مطابقة للي عندك
COPY car_model.pkl .
COPY model_columns.pkl .
COPY grpc_server.py .
COPY car_predictor_pb2.py .
COPY car_predictor_pb2_grpc.py .

# فتح بورت الـ gRPC
EXPOSE 50051

CMD ["python", "grpc_server.py"]