FROM python:3.9-slim

WORKDIR /app

# تثبيت المكتبات الأساسية
RUN pip install --no-cache-dir \
    pandas \
    scikit-learn \
    joblib \
    grpcio \
    grpcio-tools

# نسخ كل الملفات
COPY . .

# تشغيل السكربت لتوليد الموديل
RUN python train_and_save.py

# فتح بورت الـ gRPC
EXPOSE 50051

CMD ["python", "grpc_server.py"]