name: Trigger auto deployment for api-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/api-service-AutoDeployTrigger-aaedccba-c101-4e61-9f80-387c70321883.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.APISERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APISERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APISERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}docker-compose.yml
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: carpriceacr2003.azurecr.io
          registryUsername: ${{ secrets.APISERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APISERVICE_REGISTRY_PASSWORD }}
          containerAppName: api-service
          resourceGroup: carprice-rg
          imageToBuild: carpriceacr2003.azurecr.io/api-service:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


